before_install: gem install bundler --version '1.10.6'

gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.0.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile

rvm:
  - "2.2.0"